### ISSUE TITLE
Возможности загрузки файлов на сервер и скачивания их по уникальному адресу

### ISSUE THREAD

**Issue by Infarh** [OpenGeekBrains/SciMaterials#3]
Обеспечить возможность загрузки файлов на сервер с помощью POST-запроса. 

Для этого предусмотреть наличие маршрута, обрабатывающего POST запрос (на пример `POST -> http://localhost/files`). В запросе предусмотреть возможность передачи имени файла.

При обработке запроса сервер должен принять файл и сохранить его на диск в указанное в конфигурации место. При загрузке файла рассчитать его хеш-сумму (MD5? SHA512?), измерить длину и определить имя файла (+ расширение). Эти метаданные должны быть сохранены в хранилище информации о доступных файлах (и, возможно, помещены в дополнительный файл метаданных рядом с принятым файлом).

Обеспечить обработку GET-запроса на заданный маршрут (адрес) для получения указанного в запросе файла. Запрос в адресе должен передать имя файла (либо хеш-сумму), а сервер обеспечить передачу этого файла запросившему его клиенту с указанием имени файла и (MIME) типа.

**Comment by Infarh** [comment]
Сразу предложение по реализации: создать MVC-контроллер для управления файлами и выполнения над ними всех необходимых файловых операций. Контроллер должен обеспечивать как WebAPI-часть, так и часть интерфейса пользвоателя.

**Comment by orlfi** [comment]
Файлы хранится на диске в куче или же необходима какая либо структура каталогов?

**Comment by Infarh** [comment]
> Файлы хранится на диске в куче или же необходима какая либо структура каталогов?

Должен быть общий каталог для всех хранимых файлов, путь к которому определяется в конфигурации.
- Дальше возможно что `имя вложенного каталога` == `название категории`
- При этом, есть возможность получить полный перечень всех хранимых файлов во всех подкаталогах файловой системы.
- Кроме того, БД должна знать обо всех хранимых в каталоге файлах с указанием их категорий.
- Должна быть предусмотрена функция восстановления каталога по БД и восстановление БД по каталогу файлов:
  - Перемещение файлов в каталог в соответствии с его категорией
  - Назначение категории файлу в соответствии с его каталогом.
- Вложенный каталог в другой каталог = подкатегория
- При извлечении всех файлов каталога у каждого файла можно получить его каталог, следовательно, можно определить его категорию.
- Должна быть функция обнаружения потерянных файлов (которые на значатся в БД).
- Должна быть функция очистки потерянных файлов (их физическое удаление).

**Comment by WolfManR** [comment]
по правилам безопасного хранения данных в интернете абсолютно все файлы в файловой системе должны быть именованы каким то уникальным идентификатором, а оригинальное имя и возможно тип должны хранится где то в мета данных
File.txt - Api - Storage -> 0f32lx32 - Storage - Api -> File.txt

**Comment by Infarh** [comment]
Актуальность файла с метаданными, который прикладывается к файлу с основной информацией, таким образом, становится выше. Но при этом надо обязательно учесть возможность рассогласованности данных. Случай отсутствия этого файла, случай разности информации в БД и в этом файле - кому верить больше?

**Comment by orlfi** [comment]
Будет вложенность категорий (дерево категорий)?

**Comment by WolfManR** [comment]
> Будет вложенность категорий (дерево категорий)?

дерева категорий не должно быть, как минимум глубокой, физический путь до файлов имеет ограничение в 260+- символов
но это дерево может быть в данных

**Comment by Infarh** [comment]
Проверить и обеспечить возможность загрузки больших файлов (больше 3 ГБ) минуя оперативную память сразу на диск.
При этом при загрузке файла должен быть вычислен ХЕШ.
