### ISSUE TITLE
Обеспечить базовый интерфейс пользователя сервиса

### ISSUE THREAD

**Issue by Infarh** [OpenGeekBrains/SciMaterials#4]
Разработать макет и базовый дизайн интерфейса пользователя, обеспечивающий доступ к основным функциональным возможностям приложения.

Интерфейс должен поддерживать единый макет представлений с Главным меню и панелью навигации.

Дизайн должен быть построен на использовании Bootstrap/jQuery/FontAwesome.

**Comment by Infarh** [comment]
Основные возможности, которые требуются на первое время:
- Возможность доступа к интерфейсу контроллера управления файлами
  - Просмотр списка загруженных файлов
  - Форма для загрузки очередного файла
  - Органы управления для просмотра деталей файла и удаления файла
- Ссылка на форму входа и регистрации
- Форма входа
- Форма регистрации

**Comment by WolfManR** [comment]
Front Structure:
 - Blazor Wasm
 - Asp.Net Host
 - Blazor Components Library
