### ISSUE TITLE
Инициализатор БД системы Identity

### ISSUE THREAD

**Issue by Infarh** [OpenGeekBrains/SciMaterials#41]
Нужен сервис, который регистрируется в контейнере сервисов основного приложения.
При запуске приложения в Program.cs этот сервис должен быть получен из контейнера сервисов и у него должен быть вызван метод `InitializeAsync`. Цель:

- Проверка существования БД (проверка применения всех миграций)
- Проверка наличия олди администратора
- Проверка наличия пользователя `Admin`

**Comment by AlexanderMeshchaninov** [comment]
Сделал.

**Comment by Infarh** [comment]
Создан https://github.com/OpenGeekBrains/SciMaterials/blob/77c578241adb64dc6332e2b67be4c3ee01f543b3/Data/SciMaterials.DAL.AUTH/InitializationDb/AuthDbInitializer.cs
в #48
