### ISSUE TITLE
Почистить проекты с миграциями БД под Identity

### ISSUE THREAD

**Issue by Infarh** [OpenGeekBrains/SciMaterials#46]
Для пулл-реквеста #44 почистить проекты с миграциями для БД системы Identity:

- сделать их библиотеками
- убрать из них полностью инфраструктуру web-приложения
- убрать файл конфигурации
- убрать все лишние пакеты кроме пакета с профильным провайдером БД (если проект под Sqlite, то в нём должен быть провайдер под Sqlite)

В проект с контекстом БД для системы Identity добавить сервис инициализатора БД.
Сервис должен представлять собой класс, в конструкторе которого нужно получить из IoC
- контекст БД
- менеджеры Identity
- логгер

В классе должен быть нестатический асинхронный метод `InitializeAsync(CancelationToken Cancel = default)` внутри которого необходимо
- вызвать `await _db.Database.MigrateAsync()` для создания БД в случае её отсутствия и миграции к последней версии
- заполнение БД минимальным необходимым набором данных в случае его отсутствия (на пример проверка наличия пользователя Admin)

Сервис инициализации должен быть зарегистрирован в главном приложении в его контейнере сервисов и выполнен сразу после вызова `var app = builder.Build();` в `Program.cs`

Инициализатор будет инициализировать ту базу данных, которая зарегистрирована в IoC приложения.

**Comment by AlexanderMeshchaninov** [comment]
В процессе...
