### ISSUE TITLE
Создать предметную область и её логику

### ISSUE THREAD

**Issue by Infarh** [OpenGeekBrains/SciMaterials#6]
Определить основные понятия системы. Такие как:

- Ресурс
  - Файл
  - URL-адрес
- Категория (или раздел)
- Ключевое слово
- Пользователь (должен быть отдельным от пользователя в системе безопасности, но связан с ним идентификатором)
- Комментарий

Обеспечить средства для хранения и доступа к данным этих моделей.

**Comment by orlfi** [comment]
что подразумевается под: "Обеспечить средства для хранения и доступа к данным этих моделей."?

**Comment by Infarh** [comment]
> что подразумевается под: "Обеспечить средства для хранения и доступа к данным этих моделей."?

Некий сервис, реализующий интерфейс репозитория.

**Comment by orlfi** [comment]
ок

**Comment by Infarh** [comment]
Перечень моделей предметной области:
- Ресурс
  - Файл
  - URL-адрес
  - HTML-текст
- Пользователь
- Роль
- Комментарий
- Раздел
- Ключевое слово (Tag)

**Comment by Infarh** [comment]
Необходимо описание (интерфейс) и реализация сервиса хранилища сущностей/моделей - репозиторий с CRUD-интерфейсом

**Comment by Infarh** [comment]
Определить модель файла метаданных, хранимых вместе с файлом на диске.
Определить необходимый набор информации в модели.

**Comment by Infarh** [comment]
Пока откладываем до завершения реализации базовой логики проекта
