### ISSUE TITLE
Создать инфраструктуру для взаимодействия с Базой данных

### ISSUE THREAD

**Issue by Infarh** [OpenGeekBrains/SciMaterials#7]
Реализовать слой данных на основе Entity Framework

- [x] Реализовать возможности использования различных БД

- [x] Реализовать контекст данных и набор сущностей к нему.

- [x] Обеспечить максимальную изоляцию слоя БД от остальных частей приложения. Слой БД должен быть самодостаточным и не нуждаться ни в каких других частях кода проекта.

- [x] Обеспечить возможность автоматизированной инициализации БД при запуске приложения (с возможностью полностью удалить и пересоздать БД в СУБД).

- [x] Обеспечить конфигурируемость подключения к БД по средствам строки подключения, хранимой в системе конфигурации всего приложения (конфигурация подключения к БД не должна быть частью слоя данных и не должна быть жёстко закодирована в контексте БД).

- [x] Обеспечить систему миграций БД для каждой поддерживаемой БД.

**Comment by Infarh** [comment]
1. Контекст БД + система сущностей
2. Провайдеры подключения к СУБД + миграции + код методов-расширения для регистрации контекста БД в контейнере сервисов
3. Инициализатор БД + набор тестовых данных к нему

**Comment by RosGoodman** [comment]
Уточнить:
необходимость хранения формата файла в виде отдельной сущности.
