### ISSUE TITLE
Требуется настройка CI/CD автоматизации сборки проекта и запуска модульных тестов

### ISSUE THREAD

**Issue by Infarh** [OpenGeekBrains/SciMaterials#9]
Требуется сконфигурировать сценарий автоматизации компиляции и запуска модульных тестов на GitHub

**Comment by Infarh** [comment]
Примерный алгоритм:
![image](https://user-images.githubusercontent.com/595602/193305317-3e7566d9-54e4-4b83-8995-ff2ed963f6ba.png)
Выбрать обычный .NET проект
![image](https://user-images.githubusercontent.com/595602/193305488-6df8be0f-2fa0-4833-a018-7d7e3f45de78.png)

Пока нет WPF-проекта, можно обойтись простым скриптом
![image](https://user-images.githubusercontent.com/595602/193306150-099e59c6-4429-424b-a6f3-491b6b14a4e8.png)

**Comment by nickchuchunov** [comment]
- Подписание сборки строгим именем
- генерация открытого и закрытого ключа с помощью утилиты sn.exe
- именование сборок ( правила присвоения : простого имени, версии, культуры, маркера открытого ключа)
- написать функцию (с атрибутом static) с использованием объекта Assembly и его свойства FullName которое возвращает имя сборки
- написать функцию (с атрибутом static) с использованием класса AssemlyName для редактирования имени сборки
- обсудить как задавать атрибут AssemblyInformationlVersion (версия отображаемая конечному пользователю в поле Product Version
- обсудить как задавать атрибут AssemblyFileVersion (отображение в поле FileVersion)
  
- ГЛАВНОЕ
- обсудить нужно ли редактировать файл .resources (с помощью файла .resx) для доступа к сборкам через URL (возможность собирать проект из модулей - сборок) 
 с использованием метода Application.GetResourceSream 
- ЗАГРУЖАТЬ СБОРКИ ПРОГРАММНОЙ ЛОГИКОЙ
- для поиска сборок можно использовать класс AsesemlyLoadContext (а для загрузки его методы LoadFromAssemlyPath и LoadFromStream )
- можно использовать класс AssembllyLoadContext и его метод LoadFromAssemlyName
- Обсудить как правильно написать Assemli Load Context ( С учетом проведения модульных тестов)

**Comment by nickchuchunov** [comment]
name: merge_test

on:
  push:
    branches: [ "dev" ]
 

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3 
    #извлечение репозиторя в бегун
    - name: Setup .NET
      uses: actions/setup-dotnet@v3 
      with:
        dotnet-version: 6.0.x 
        #Загрузка среды Dotnet 6
    - name: Restore dependencies
      run: dotnet restore
      #Восстановление зависимостей для проекта 
    - name: Build
      run: dotnet build --no-restore
      # Сборка проекта и все его зависимости с отключенным восстановлением зависимостей проекта --no-restore
    - name: Test
    # Запуск стандартных модульных тестов для всего проекта
      run: dotnet test --no-build --verbosity normal
      #Запуск тестов из проекта (Test папка в проекте)
    - name: TestSciMaterials
      run: dotnet test Tests -c Release --nologo --no-build

**Comment by nickchuchunov** [comment]
name: merge_test

on:
  push:
    branches: [ "dev" ]
 

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3 
    #извлечение репозиторя в бегун
    - name: Setup .NET
      uses: actions/setup-dotnet@v3 
      with:
        dotnet-version: 6.0.x 
        #Загрузка среды Dotnet 6
    - name: Restore dependencies
      run: dotnet restore
      #Восстановление зависимостей для проекта 
    - name: Build
      run: dotnet build 
      # Сборка проекта и все его зависимости (отключенние воостановление зависимостей проекта --no-restore)
    - name: Test
    # Запуск стандартных модульных тестов для всего проекта
      run: dotnet test --no-build --verbosity normal
      #Запуск тестов из проекта (Test папка в проекте)
    - name: TestSciMaterials
      run: dotnet test Tests -c Release --nologo --no-build

**Comment by nickchuchunov** [comment]
SciMaterials/.github/workflows/dotnet.yml

Для автоматизации сборки в git !

Понятно что проект будет собиратся при merge в ветку dev .

Но как будут проводится тесты  описанные в проекте - не понятно.

**Comment by nickchuchunov** [comment]
name: merge_test

on:
  push:
    branches: [ "dev" ]
 

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v3 
    #извлечение репозиторя в бегун
    - name: Setup .NET
      uses: actions/setup-dotnet@v3 
      with:
        dotnet-version: 6.0.x 
        #Загрузка среды Dotnet 6
    - name: Restore dependencies
      run: dotnet restore
      # загрузка nuget пакетов 
      - name: Install dependencies
      - run: dotnet add package AutoMapper --version 12.0.0 
      - run: dotnet add package Microsoft.Extensions.DependencyInjection --version 12.0.0
      - run: dotnet add package Blazored.LocalStorage --version 4.2.0
      - run: dotnet add package bunit --version 1.10.14
      - run: dotnet add package coverlet.collector --version 3.1.2
      - run: dotnet add package Microsoft.AspNetCore.Authentication.JwtBearer --version 6.0.9
      - run: dotnet add package Microsoft.AspNetCore.Components.WebAssembly --version 6.0.9
      - run: dotnet add package Microsoft.AspNetCore.Components.WebAssembly.Authentication --version 6.0.9
      - run: dotnet add package Microsoft.AspNetCore.Components.WebAssembly.DevServer --version 6.0.9
      - run: dotnet add package Microsoft.AspNetCore.Components.WebAssembly.Server --version 6.0.9
      - run: dotnet add package Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore --version 6.0.9
      - run: dotnet add package Microsoft.AspNetCore.Identity.EntityFrameworkCore --version 6.0.9
      - run: dotnet add package Microsoft.AspNetCore.Identity.UI --version 6.0.9
      - run: dotnet add package Microsoft.AspNetCore.Mvc.Testing --version 6.0.9
      - run: dotnet add package Microsoft.EntityFrameworkCore --version 6.9.0
      - run: dotnet add package Microsoft.EntityFrameworkCore.Design --version 6.0.9
      - run: dotnet add package Microsoft.EntityFrameworkCore.InMemory --version 6.0.9
      - run: dotnet add package Microsoft.EntityFrameworkCore.Sqlite --version 6.0.9
      - run: dotnet add package Microsoft.EntityFrameworkCore.SqlServer --version 6.0.9
      - run: dotnet add package Microsoft.EntityFrameworkCore.Tools --version 6.0.9
      - run: dotnet add package Microsoft.Extensions.Configuration.UserSecrets --version 6.0.1
      - run: dotnet add package Microsoft.Extensions.DependencyInjection --version 6.0.0
      - run: dotnet add package Microsoft.Extensions.Hosting --version 6.0.1
      - run: dotnet add Microsoft.Extensions.Http --version 6.0.0
      - run: dotnet add Microsoft.Extensions.Logging.Abstractions --version 6.0.2
      - run: dotnet add Microsoft.NET.Test.Sdk --version 17.3.2
      - run: dotnet add Moq --version 4.18.2
      - run: dotnet add MudBlazor --version 6.0.17
      - run: dotnet add Newtonsoft.Json --version 13.0.1
      - run: dotnet add NLog --version 5.0.4
      - run: dotnet add Npgsql.EntityFrameworkCore.PostgreSQL --version 6.0.7
      - run: dotnet add Pomelo.EntityFrameworkCore.MySql --version 6.0.2
      - run: dotnet add Swashbuckle.AspNetCore --version 6.4.0
      - run: dotnet add System.IdentityModel.Tokens.Jwt --version 6.23.1
      - run: dotnet add System.Net.Http.Json --version 6.0.0
      - run: dotnet add xunit --version 2.4.2
      - run: dotnet add xunit.runner.visualstudio --version 2.4.5
      #Восстановление зависимостей для проекта 
    - name: Build
      run: dotnet build 
      # Сборка проекта и все его зависимости (отключенние воостановление зависимостей проекта --no-restore)
    - name: Test
    # Запуск стандартных модульных тестов для всего проекта
      run: dotnet test --no-build --verbosity normal
      #Запуск тестов из проекта (Test папка в проекте)
    - name: TestSciMaterials
      run: dotnet test Tests -c Release --nologo --no-build

**Comment by nickchuchunov** [comment]
name: merge_test

on:
  push:
    branches: [ "dev" ]
 

jobs:
  build:
    #тип бегуна
    runs-on: windows-latest


    steps:
    - uses: actions/checkout@v3 
    #извлечение репозиторя в бегун
    - name: Setup .NET
      uses: actions/setup-dotnet@v3 
      with:
        dotnet-version: 6.0.x 
        #Загрузка среды Dotnet 6
    - name: Restore dependencies
      run: dotnet restore
      # загрузка nuget пакетов 
      - name: Install dependencies
      - run: dotnet add package AutoMapper --version 12.0.0 
      - run: dotnet add package Microsoft.Extensions.DependencyInjection --version 12.0.0
      - run: dotnet add package Blazored.LocalStorage --version 4.2.0
      - run: dotnet add package bunit --version 1.10.14
      - run: dotnet add package coverlet.collector --version 3.1.2
      - run: dotnet add package Microsoft.AspNetCore.Authentication.JwtBearer --version 6.0.9
      - run: dotnet add package Microsoft.AspNetCore.Components.WebAssembly --version 6.0.9
      - run: dotnet add package Microsoft.AspNetCore.Components.WebAssembly.Authentication --version 6.0.9
      - run: dotnet add package Microsoft.AspNetCore.Components.WebAssembly.DevServer --version 6.0.9
      - run: dotnet add package Microsoft.AspNetCore.Components.WebAssembly.Server --version 6.0.9
      - run: dotnet add package Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore --version 6.0.9
      - run: dotnet add package Microsoft.AspNetCore.Identity.EntityFrameworkCore --version 6.0.9
      - run: dotnet add package Microsoft.AspNetCore.Identity.UI --version 6.0.9
      - run: dotnet add package Microsoft.AspNetCore.Mvc.Testing --version 6.0.9
      - run: dotnet add package Microsoft.EntityFrameworkCore --version 6.9.0
      - run: dotnet add package Microsoft.EntityFrameworkCore.Design --version 6.0.9
      - run: dotnet add package Microsoft.EntityFrameworkCore.InMemory --version 6.0.9
      - run: dotnet add package Microsoft.EntityFrameworkCore.Sqlite --version 6.0.9
      - run: dotnet add package Microsoft.EntityFrameworkCore.SqlServer --version 6.0.9
      - run: dotnet add package Microsoft.EntityFrameworkCore.Tools --version 6.0.9
      - run: dotnet add package Microsoft.Extensions.Configuration.UserSecrets --version 6.0.1
      - run: dotnet add package Microsoft.Extensions.DependencyInjection --version 6.0.0
      - run: dotnet add package Microsoft.Extensions.Hosting --version 6.0.1
      - run: dotnet add Microsoft.Extensions.Http --version 6.0.0
      - run: dotnet add Microsoft.Extensions.Logging.Abstractions --version 6.0.2
      - run: dotnet add Microsoft.NET.Test.Sdk --version 17.3.2
      - run: dotnet add Moq --version 4.18.2
      - run: dotnet add MudBlazor --version 6.0.17
      - run: dotnet add Newtonsoft.Json --version 13.0.1
      - run: dotnet add NLog --version 5.0.4
      - run: dotnet add Npgsql.EntityFrameworkCore.PostgreSQL --version 6.0.7
      - run: dotnet add Pomelo.EntityFrameworkCore.MySql --version 6.0.2
      - run: dotnet add Swashbuckle.AspNetCore --version 6.4.0
      - run: dotnet add System.IdentityModel.Tokens.Jwt --version 6.23.1
      - run: dotnet add System.Net.Http.Json --version 6.0.0
      - run: dotnet add xunit --version 2.4.2
      - run: dotnet add xunit.runner.visualstudio --version 2.4.5
      #Восстановление зависимостей для проекта 
    - name: Build
      run: dotnet build 
      # Сборка проекта и все его зависимости (отключенние воостановление зависимостей проекта --no-restore)
    - name: Test
    # Запуск стандартных модульных тестов для всего проекта
      run: dotnet test --no-build --verbosity normal
      #Запуск тестов из проекта (Test папка в проекте)
    - name: TestSciMaterials
      run: dotnet test Tests -c Release --nologo --no-build

**Comment by Infarh** [comment]
Автоматизация запуска компиляции и модульного тестирования работает.
